dist: trusty

language: c

addons:
  apt:
    sources:
    - sourceline: 'ppa:team-gcc-arm-embedded/ppa'
    packages:
    - gcc-arm-embedded

script:
  - make release OUT=bcf-kit-sigfox-co2-monitor-${TRAVIS_TAG} VERSION=${TRAVIS_TAG}
  - cp decode.py out/release/bcf-kit-sigfox-co2-monitor-${TRAVIS_TAG}.py
deploy:
  skip_cleanup: true
  file_glob: true
  file:
    - out/release/*.bin
    - decode.py
  api_key: ${GITHUB_KEY}
  provider: releases
  overwrite: true
  on:
    tags: true
