article: https://github.com/bigclownlabs/bcf-kit-sigfox-co2-monitor/blob/master/README.md
assembly:
  - name: HARDWARIO Core Module
  - name: HARDWARIO Sigfox Module
  - name: HARDWARIO CO2 Module
  - name: HARDWARIO Mini Battery Module
    optional: true
  - name: HARDWARIO Battery Module
    optional: true    
