article: https://github.com/bigclownlabs/bcf-kit-sigfox-co2-monitor/blob/master/README.md
assembly:
  - name: BigClown Core Module
  - name: BigClown Sigfox Module
  - name: BigClown CO2 Module
  - name: BigClown Mini Battery Module
    optional: true
  - name: BigClown Battery Module
    optional: true    
